version: '3.8'

networks:
  internal_network:
    internal: true
  external_network:
    driver: bridge

services:
  # jenkins - for workflow manager
  jenkins:
    image: jenkins/jenkins:2.462.3-lts
    user: root
    container_name: we-jenkins
    platform: linux/amd64
    restart: unless-stopped
    networks:
      - internal_network
      - external_network
    ports:
      - target: 8080
        published: 9800
        protocol: tcp
      - "8080:8080" # or any other required port mapping
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - ./init.groovy.d:/usr/share/jenkins/ref/init.groovy.d
    environment:
      # Jenkins Admin 설정
      JENKINS_ADMIN_ID: admin
      JENKINS_ADMIN_PASSWORD: 1234567
      JAVA_OPTS: -Djenkins.install.runSetupWizard=false
    healthcheck: # for workflow-manager
      test: [ "CMD", "curl", "-f", "http://localhost:8080/login" ]
      interval: 1m
      timeout: 5s
      retries: 3
      start_period: 120s

  # workflow-manager
  mc-workflow-manager:
    image: cloudbaristaorg/mc-workflow-manager:edge
    container_name: workflow-manager
    depends_on:
      jenkins:
        condition: service_healthy
    networks:
      - external_network
    ports:
      - target: 18083
        published: 18083
        protocol: tcp
    volumes:
      - ./document:/document # -v ${PROJECT_PATH}/document:/document
    environment:
      - DB_INIT_YN=create # create, update, create-drop, none ....
      - DB_ID=workflow
      - DB_PW=workflow!23
      - SQL_DATA_INIT=always # SQL_DATA_INIT=never
    healthcheck: # for cb-workflow-manager
      test: ["CMD", "curl", "-f", "http://localhost:18083/readyz"]
      interval: 1m
      timeout: 5s
      retries: 3
      start_period: 10s
