version: '3.8'

networks:
  internal_network:
    internal: true
  external_network:
    driver: bridge

services:
  # jenkins - for workflow manager
  jenkins:
    image: bitnami/jenkins:2.462.3
    user: root
    container_name: we-jenkins
    platform: linux/amd64
    networks:
      - internal_network
      - external_network
    ports:
      - target: 8080
        published: 9800
        protocol: tcp
      - "8080:8080" # or any other required port mapping
    volumes:
      - ./jenkins_home:/bitnami/jenkins/home # -v $HOME/mcmp/oss/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker # -v $(which docker):/usr/bin/docker
    environment:
      JENKINS_USERNAME: admin
      JENKINS_PASSWORD: 123456
      JENKINS_PLUGINS: >-
        workflow-api,
        swarm,
        authorize-project,
        antisamy-markup-formatter,
        pipeline-github-lib,
        pipeline-rest-api,
        git,
        github-branch-source,
        gradle,
        pipeline-model-definition,
        pipeline-build-step,
        workflow-aggregator,
        matrix-project,
        email-ext,
        durable-task,
        checks-api,
        build-timeout,
        timestamper,
        ws-cleanup,
        ssh-slaves
    healthcheck: # for workflow-manager
      test: [ "CMD", "curl", "-f", "http://localhost:8080/login" ]
      interval: 1m
      timeout: 5s
      retries: 3
      start_period: 10s

  # workflow-manager
  mc-workflow-manager:
    image: cloudbaristaorg/mc-workflow-manager:edge
    container_name: workflow-manager
    depends_on:
      jenkins:
        condition: service_healthy
    networks:
      - external_network
    ports:
      - target: 18083
        published: 18083
        protocol: tcp
    volumes:
      - ./document:/document # -v ${PROJECT_PATH}/document:/document
    environment:
      - DB_INIT_YN=create # create, update, create-drop, none ....
      - DB_ID=workflow
      - DB_PW=workflow!23
      - SQL_DATA_INIT=always # SQL_DATA_INIT=never
    healthcheck: # for cb-workflow-manager
      test: ["CMD", "curl", "-f", "http://localhost:18083/readyz"]
      interval: 1m
      timeout: 5s
      retries: 3
      start_period: 10s
